spring:
  # MySQL RDS Database 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://<RDS Endpoint>:<DB Port>/<DB NAME>
    username: <Username>  # Parameter Store
    password: <Password>  # Parameter Store

  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true

    config:
      import: aws-parameterstore:/<Parameter Name Prefix>/

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE

jwt:
  secret:
    key: <JWT Secret Key>

# s3
cloud:
  aws:
    credentials:
      accessKey: <AWS IAM user Access Key>  # Parameter Store
      secretKey: <AWS IAM user Secret Key>  # Parameter Store
    region:
      static: <AWS S3 bucket region>
    s3:
      bucket: <AWS S3 bucket name>
      presigned-url-expiration: <Expiration Minutes>