spring:
  # MySQL RDS Database 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://<RDS Endpoint>:<DB Port>/<DB NAME>
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE

jwt:
  secret:
    key: jwt-secret-key